#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

ENV_FILE=/dev/null
LOGIN_URL_PATTERN='https://ampcode\.com/auth/cli-login\?authToken=[[:xdigit:]]+'
AMP_LOGIN_PID=""
WORK_DIR=""

usage() {
  printf '%s\n' \
    'Usage: amp-login-wizard.sh <t1|mac>' \
    '' \
    '  t1   Start a fresh Amp login and exchange its authorization over Magic Wormhole.' \
    '  mac  Receive the URL, open it, and return the authorization code.'
}

fail() {
  printf '  %s✗ %s%s\n' "$RED" "$1" "$RESET" >&2
  exit 1
}

require_command() {
  command -v "$1" >/dev/null 2>&1 || fail "$1 is required but is not available."
}

cleanup_t1() {
  exec 3>&- || true
  exec 4<&- || true

  if [[ -n ${AMP_LOGIN_PID:-} ]] && kill -0 "$AMP_LOGIN_PID" 2>/dev/null; then
    kill "$AMP_LOGIN_PID" 2>/dev/null || true
    wait "$AMP_LOGIN_PID" 2>/dev/null || true
  fi

  if [[ -n ${WORK_DIR:-} && -d $WORK_DIR ]]; then
    rm -rf -- "$WORK_DIR"
  fi

  AMP_LOGIN_PID=""
  WORK_DIR=""
  LOGIN_URL=""
  AMP_AUTH_CODE=""
  RETURN_WORMHOLE_CODE=""
}

run_t1() {
  local line amp_status

  TOTAL_STAGES=4
  banner "Amp login · T1"

  stage "Preflight and fresh login"
  require_command amp
  require_command mkfifo
  require_command wormhole
  say "Starting a new Amp login without tmux capture or clipboard state."

  umask 077
  WORK_DIR=$(mktemp -d)
  mkfifo "$WORK_DIR/amp-input" "$WORK_DIR/amp-output"
  trap cleanup_t1 EXIT
  trap 'exit 130' INT TERM HUP

  amp login <"$WORK_DIR/amp-input" >"$WORK_DIR/amp-output" 2>&1 &
  AMP_LOGIN_PID=$!
  exec 3>"$WORK_DIR/amp-input"
  exec 4<"$WORK_DIR/amp-output"

  LOGIN_URL=""
  while IFS= read -r line <&4; do
    line=${line//$'\r'/}
    if [[ $line =~ $LOGIN_URL_PATTERN ]]; then
      LOGIN_URL=${BASH_REMATCH[0]}
      break
    fi
  done

  if [[ -z $LOGIN_URL ]]; then
    if wait "$AMP_LOGIN_PID"; then amp_status=0; else amp_status=$?; fi
    AMP_LOGIN_PID=""
    fail "Amp exited with status $amp_status before producing a login URL."
  fi
  say "Captured the fresh URL from this Amp process."

  stage "Send login URL"
  say "On the Mac, start this wizard in mac mode."
  note "The four-word code below is single-use and may be entered visibly."
  printf %s "$LOGIN_URL" |
    wormhole send --code-length 4 --no-qr --text -
  LOGIN_URL=""

  stage "Receive authorization"
  ask RETURN_WORMHOLE_CODE "Enter the return Wormhole code shown on the Mac:"
  [[ -n $RETURN_WORMHOLE_CODE ]] || fail "A Wormhole code is required."
  AMP_AUTH_CODE=$(wormhole receive --only-text "$RETURN_WORMHOLE_CODE")
  RETURN_WORMHOLE_CODE=""
  [[ -n $AMP_AUTH_CODE ]] || fail "The received Amp authorization code was empty."
  [[ $AMP_AUTH_CODE != *$'\n'* ]] || fail "The received authorization contained multiple lines."

  stage "Complete Amp login"
  say "Sending the authorization directly to the Amp process that issued the URL."
  printf '%s\n' "$AMP_AUTH_CODE" >&3
  AMP_AUTH_CODE=""
  exec 3>&-

  while IFS= read -r line <&4 || [[ -n $line ]]; do
    line=${line//$'\r'/}
    [[ -n $line ]] && say "$line"
  done
  exec 4<&-

  if wait "$AMP_LOGIN_PID"; then amp_status=0; else amp_status=$?; fi
  AMP_LOGIN_PID=""
  [[ $amp_status -eq 0 ]] || fail "Amp login failed with status $amp_status."

  cleanup_t1
  trap - EXIT INT TERM HUP
  finish
}

run_mac() {
  TOTAL_STAGES=4
  banner "Amp login · Mac"

  stage "Preflight"
  require_command wormhole
  say "This side receives the T1 login URL and returns its browser authorization."
  note "No value is read from or written to the macOS clipboard automatically."

  stage "Receive login URL"
  ask OUTBOUND_WORMHOLE_CODE "Enter the four-word Wormhole code shown on T1:"
  [[ -n $OUTBOUND_WORMHOLE_CODE ]] || fail "A Wormhole code is required."
  LOGIN_URL=$(wormhole receive --only-text "$OUTBOUND_WORMHOLE_CODE")
  OUTBOUND_WORMHOLE_CODE=""
  [[ $LOGIN_URL =~ ^${LOGIN_URL_PATTERN}$ ]] || fail "T1 sent an unexpected login URL."

  stage "Authorize in browser"
  open_url "$LOGIN_URL"
  LOGIN_URL=""
  step "Complete Amp authentication in the browser."
  step "Copy the authorization code shown by Amp."
  ask_secret AMP_AUTH_CODE "Paste the Amp authorization code, then press Return:"
  [[ -n $AMP_AUTH_CODE ]] || fail "The Amp authorization code is required."

  stage "Return authorization"
  say "Enter the four-word code below into the waiting T1 wizard."
  note "This command remains open until T1 receives the authorization."
  printf %s "$AMP_AUTH_CODE" |
    wormhole send --code-length 4 --no-qr --text -
  AMP_AUTH_CODE=""

  finish
}

case ${1:-} in
  t1)
    run_t1
    ;;
  mac)
    run_mac
    ;;
  -h | --help)
    usage
    ;;
  *)
    usage >&2
    exit 2
    ;;
esac
